# ./book-deploy-bi.yml
---

- hosts: all
  gather_facts: true
  user: root

  roles:
    - role: prepare
    - role: repo
#    - role: repo_local
    - role: app
    - role: filesystem
    - role: database
#    - role: firewall
    - role: finalize
