---

- name: Настраиваем Luxms BI Database
  postgresql_query:
    query: "{{ pg_user_settings_mod }}"
    db: 'mi'
    login_host: '127.0.0.1'
    port: '5432'
    login_user: 'bi'
    login_password: 'bi'
