# roles/prepare/tasks/main.yml
---

- name: "Output 'ansible_os_family'"
  debug:
    var: ansible_os_family

- name: "Output 'ansible_distribution'"
  debug:
    var: ansible_distribution

- name: "Output 'ansible_distribution_major_version'"
  debug:
    var: ansible_distribution_major_version

- name: "Output 'PostgreSQL Version'"
  debug:
    var: PG_VER

- name: Install sudo
  package:
    name: sudo
    state: present

- name: "Allow the root user to run sudo"
  lineinfile:
    path: "/etc/sudoers.d/root"
    line: "root ALL=(ALL:ALL) ALL"
    create: yes

- name: Install ca-certificates
  package:
    name: ca-certificates
    state: latest