# roles/database/tasks/postgresql_shell.yml
---

- name: Setting the password for the adm user (web interface)
  shell: psql -d postgresql://bi:bi@127.0.0.1:5432/mi -c "SELECT adm.create_user('Default Admin','adm','{{ adm_password }}','','','','{}','{}',false);"
  when: adm_password | default('') != ''

- name: Make a backup copy of mi if the database already existed on the mounted volume
  block:

  - name: Getting the size of the mi databas
    shell: psql -d postgresql://bi:bi@127.0.0.1:5432/mi -t -c "SELECT pg_database_size('mi');"
    register: mi_size

  - name: Create variables for the free space of the section with the database and the weight of the database itself
    set_fact:
      dev_size_available: "{{ (ansible_mounts | selectattr('device','equalto',dev_path) | list | first)['size_available'] | int }}"
      size_mi_base: "{{ mi_size.stdout | trim | int }}"

  - name: Create a database dump if its size does not exceed the free space of the partition
    shell: "pg_dump mi -Fc -f /data/pgbackup/mi-{{ ansible_date_time.epoch }}.bak"
    become: yes
    become_user: postgres
    become_flags: -i

  when:
    - dev_path | default('') != ''
    - pg_contents["stdout_lines"] | length > 0