# roles/database/tasks/postgresql_module.yml
---

- name: Setting the password for the adm user (web interface)
  postgresql_query:
    query: "SELECT adm.create_user('Default Admin','adm','{{ adm_password }}','','','','{}','{}',false);"
    db: 'mi'
    login_host: '127.0.0.1'
    port: '5432'
    login_user: 'bi'
    login_password: 'bi'
  when: adm_password | default('') != ''

- name: Make a backup copy of mi if the database already existed on the mounted volume
  block:

  - name: Getting the size of the mi database
    postgresql_query:
      query: "select pg_database_size('mi');"
      db: 'mi'
      login_host: '127.0.0.1'
      port: '5432'
      login_user: 'bi'
      login_password: 'bi'
    register: mi_size

  - name: Let's create variables for the free space of the section with the database and the weight of the database itself
    set_fact:
      dev_size_available: "{{ (ansible_mounts | selectattr('device','equalto',dev_path) | list | first)['size_available'] | int }}"
      size_mi_base: "{{ mi_size.query_result.0.pg_database_size | int }}"

  - name: Create a database dump if its size does not exceed the free space of the partition
    postgresql_db:
      name: 'mi'
      state: dump
      target: "/data/pgbackup/mi-{{ ansible_date_time.epoch }}.bak"
      dump_extra_args: -Fc
    become: yes
    become_user: postgres
    become_flags: -i
    when: dev_size_available >= size_mi_base

  when:
    - dev_path | default('') != ''
    - pg_contents["stdout_lines"] | length > 0