---

- name: "Создаем файловую систему ext4 для раздела {{ dev_path }}"
  filesystem:
    fstype: ext4
    dev: "{{ dev_path }}"
  when: dev_path | default('') != ''

- name: "Монтируем {{ dev_path }} в /data"
  mount:
    path: /data
    src: "{{ dev_path }}"
    fstype: ext4
    opts: defaults
    state: mounted
  when: dev_path | default('') != ''

- name: Создаем каталог для данных PostgreSQL
  file:
    path: "/data/pgdata"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700

- name: Создаем каталог для бэкапов PostgreSQL
  file:
    path: "/data/pgbackup"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700

- name: Создаем каталог для логов
  file:
    path: "/data/log/ansible"
    state: directory
    owner: postgres
    group: postgres
    mode: 0750

- name: Задаем контекст каталога /data/pgdata для PostgreSQL
  sefcontext:
    target: '/data/pgdata(/.*)?'
    setype: postgresql_db_t
    state: present
  when: > 
    ansible_os_family == "Rocky" or
    ansible_os_family == "RedHat"

- name: Задаем контекст каталога /data для PostgreSQL
  sefcontext:
    target: '/data'
    setype: postgresql_db_t
    state: present
  when: > 
    ansible_os_family == "Rocky" or
    ansible_os_family == "RedHat"

- name: Применяем контекст для каталога
  command: restorecon -irv /data
  when: > 
    ansible_os_family == "Rocky" or
    ansible_os_family == "RedHat"

- name: Обновляем факты, чтобы появилась информация о подмонтированном томе
  setup: