[general]
log-level = "info"
log-flags = "msgprefix"
log-output = "stderr"
color = "never"
number-of-retries = 3
retry-timeout = "5s"

[redis]
address = "localhost:6379"
user = ""
password = ""
rdb = 0

[nats]
address = "localhost:4222"
user = ""
password = ""

[postgres.0]
enabled = true
channels = ["luxmsbi.cdc.audit.events", "luxmsbi.cdc.audit.admin_events", "ldb.runs"]
conn-string = "host=localhost port=5432 dbname=mi pool_max_conns=10 user=bi password=bi"
schema = ""
table = ""
timeout = "30s"
max-batch-size = 1
max-queue = 100
flush-interval = "5s"