# roles/prepare/defaults/main.yml
---

PG_VER_ARRAY:
  RED:
    "7": "15"
    "8": "17"
  REDOS:
    "7": "15"
    "8": "17"
  Astra Linux:
    "1.7": "13"
    "1.7_x86-64": "13"
    "1": "15"
  Altlinux:
    "10": "15"
  Rocky:
    "8": "15"
    "9": "17"
  RedHat:
    "8": "15"
    "9": "17"
  MosOS Arbat:
    "15": "15"

PG_VER: "{{ PG_VER_ARRAY[ansible_os_family][ansible_distribution_major_version] }}"

PG_BIN_DIR:
  RED: /usr/pgsql-{{ PG_VER }}/bin
  REDOS: /usr/pgsql-{{ PG_VER }}/bin
  Astra Linux: /usr/lib/postgresql/{{ PG_VER }}/bin
  Altlinux: /usr/bin
  Rocky: /usr/bin
#  RedHat: /usr/bin
  RedHat:
    "8": /usr/bin
    "9": /usr/pgsql-17/bin
  MosOS Arbat: /usr/pgsql-{{ PG_VER }}/bin