# roles/app/tasks/main.yml
---

- name: Creating a directory for temporary storage of installation files Luxms BI
  file:
    path: /opt/lux-upd/install/tmp
    state: directory

- name: Install and Start Supplementary Packagies on RPM / ALT
  block:

  - name: "Install supplementary packagies on RPM / ALT"
    package:
      name:
        - nats-server
        - keydb
      state: present

  when: ansible_os_family is not match("Astra Linux*")

- name: Install and Start Supplementary Packagies and setting nginx preferences on Astra Linux
  block:

  - name: "Install supplementary packagies on Astra Linux"
    package:
      name:
        - nats-server
        - keydb-server
      state: present

#  - name: Запрещает автозапуск для nginx
#    lineinfile:
#      dest: /lib/systemd/system-preset/90-systemd.preset
#      line: "disable nginx.service"
#      owner: root
#      state: present
#      insertafter: EOF

#  - name: Настраиваем preferences для apt nginx
#    copy:
#      src: nginx.apt-preference
#      dest: /etc/apt/preferences.d/nginx
#      owner: root
#      group: root
#      mode: '0644'

  when: ansible_os_family == "Astra Linux"


- name: Install Chromium in MosOS
  shell: zypper in --force-resolution -y chromium
  when: ansible_os_family is match("MosOS*")


- name: "Install Luxms BI packagies"
  package:
    name: "{{ item }}"
    state: present
  loop:
    - luxmsbi-web
#    - luxmsbi-web=11.1.28-20250909~alse1.7
    - luxmsbi-appserver-mono
    - luxmsbi-gateway
    - luxmsbi-pumpushka
    - luxmsbi-docs
    - luxms-databoring

- name: Collect information about the services on the server
  service_facts:

- name: "Stop systemd units"
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  when: ansible_facts.services["{{ item }}.service"] is defined
  loop:
    - luxmsbi-web
    - luxmsbi-headless-chrome
    - luxmsbi-gateway
    - luxmsbi-appserver
    - luxmsbi-pumpushka
    - luxms-databoring
    - nats-server
    - keydb-server
    - keydb
    - nginx

- name: "Use the configuration file to configure the 'luxmsbi-pumpushka'"
  copy:
    src: luxmsbi-pumpushka.conf
    dest: /opt/luxmsbi/conf/
    mode: 0640
    owner: bi

- name: Install PostgreSQL on RedOS
  block:

  - name: "Install PostgreSQL and psycopg"
    yum:
      name:
        - "postgresql{{ PG_VER }}"
        - "postgresql{{ PG_VER }}-server"
        - "postgresql{{ PG_VER }}-contrib"
        - 'python3-psycopg2'
      state: present

  - name: "Download Luxms BI Database and DS Infosec"
    dnf:
      name:
        - "luxmsbi-pg{{ PG_VER }}"
        - "luxmsbi-pg-ds-infosec"
      download_only: true
      download_dir: /opt/lux-upd/install/tmp
      state: present

  when: ansible_os_family == "RED" or ansible_os_family == "REDOS"


- name: "Install PostgreSQL on Astra Linux 1.7"
  block:

  - name: Import postgresql repo key
    apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      state: present

  - name: Import keyserver.ubuntu.com repo keys
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 648ACFD622F3D138
      state: present

  - name: "Add postgresql-archive DEB repository for Astra Linux 1.7"
    apt_repository:
      repo: deb https://apt-archive.postgresql.org/pub/repos/apt buster-pgdg main
      filename: pgdg

  - name: "Add postgresql DEB repository for Astra Linux 1.7"
    apt_repository:
      repo: "deb https://apt.postgresql.org/pub/repos/apt bullseye-pgdg {{ PG_VER }}"
      filename: pgdg

  - name: "Install postgresql-13 and psycopg"
    apt:
      name: "{{ item }}"
      update_cache: yes
    loop:
      - "libpq5={{ PG_VER }}*"
      - "postgresql-client-{{ PG_VER }}"
      - "postgresql-{{ PG_VER }}"
      - 'python3-psycopg2'

  - name: "Download Luxms BI Database and DS Infosec"
#    shell: apt clean all && apt install -y --download-only --reinstall luxmsbi-pg{{ PG_VER }} luxmsbi-pg-ds-infosec && mv /var/cache/apt/archives/*.deb /opt/lux-upd/install/tmp/
    shell: apt clean all && apt install -y --download-only --reinstall luxmsbi-pg13=11.1.7-20250901~alse1.7 luxmsbi-pg-ds-infosec && mv /var/cache/apt/archives/*.deb /opt/lux-upd/install/tmp/
  when: ansible_os_family == "Astra Linux" and ansible_distribution_major_version == "1.7*"
 
- name: "Install PostgreSQL on Astra Linux 1.8"
  block:

  - name: Import postgresql repo key
    apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      state: present

  - name: Import keyserver.ubuntu.com repo keys
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 648ACFD622F3D138
      state: present

#  - name: "Add postgresql-archive DEB repository (ALSE 1.7)"
#    apt_repository:
#      repo: deb https://apt-archive.postgresql.org/pub/repos/apt buster-pgdg main
#      filename: pgdg

#  - name: "Add postgresql DEB repository (ALSE 1.7)"
#    apt_repository:
#      repo: "deb https://apt.postgresql.org/pub/repos/apt bullseye-pgdg {{ PG_VER }}"
#      filename: pgdg

  - name: "Install PostgreSQL-{{ PG_VER }} and psycopg"
    apt:
      name: "{{ item }}"
      update_cache: yes
    loop:
      - "libpq5={{ PG_VER }}*"
      - "postgresql-client-{{ PG_VER }}"
      - "postgresql-{{ PG_VER }}"
      - 'python3-psycopg2'

  - name: "Download Luxms BI Database and DS Infosec"
    shell: apt clean all && apt install -y --download-only --reinstall luxmsbi-pg{{ PG_VER }} luxmsbi-pg-ds-infosec && mv /var/cache/apt/archives/*.deb /opt/lux-upd/install/tmp/
  when: ansible_os_family == "Astra Linux" and ansible_distribution_major_version == "1" 

- name: "Install PostgreSQL15 on Rocky Linux 8"
  block:

    - name: "Setting the locale"
      package:
        name: glibc-langpack-ru
        state: present

    - name: "Install PostgreSQL15 on Rocky Linux 8"
      package:
        name: '{{ item }}'
        state: present
      loop:
        - '@postgresql:{{ PG_VER }}/client'
        - '@postgresql:{{ PG_VER }}/server'
        - 'postgresql-contrib'
        - 'python3-psycopg2'

    - name: "Download Luxms BI Database and DS Infosec"
      dnf:
        name:
          - 'luxmsbi-pg{{ PG_VER }}'
          - 'luxmsbi-pg-ds-infosec'
        download_only: true
        download_dir: /opt/lux-upd/install/tmp/

  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8" and PG_VER == "15"

- name: "Install PostgreSQL15 on Rocky Linux 9"
  block:

    - name: "Setting the locale"
      package:
        name: glibc-langpack-ru
        state: present

    - name: "Install PostgreSQL15 on Rocky Linux 9"
      package:
        name: '{{ item }}'
        state: present
      loop:
        - '@postgresql:{{ PG_VER }}/client'
        - '@postgresql:{{ PG_VER }}/server'
        - 'postgresql-contrib'
        - 'python3-psycopg2'

    - name: "Download Luxms BI Database and DS Infosec"
      dnf:
        name:
          - 'luxmsbi-pg{{ PG_VER }}'
          - 'luxmsbi-pg-ds-infosec'
        download_only: true
        download_dir: /opt/lux-upd/install/tmp/

  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9" and PG_VER == "15"

- name: "Install PostgreSQL17 on Rocky Linux 9"
  block:

    - name: "Setting the locale"
      package:
        name: glibc-langpack-ru
        state: present

    - name: "Install PostgreSQL17 on Rocky Linux 9 "
      package:
        name: '{{ item }}'
        state: present
      loop:
        #        - 'postgresql{{ PG_VER }}-client'
        - 'postgresql{{ PG_VER }}'
        - 'postgresql{{ PG_VER }}-server'
        - 'postgresql{{ PG_VER }}-contrib'
        - 'python3-psycopg2'

    - name: "Download Luxms BI Database and DS Infosec"
      dnf:
        name:
          - 'luxmsbi-pg{{ PG_VER }}'
          - 'luxmsbi-pg-ds-infosec'
        download_only: true
        download_dir: /opt/lux-upd/install/tmp/

  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9" and PG_VER == "17"

- name: Install PostgreSQL on ALT Linux
  block:

  - name: "Install postgresql and psycopg"
    package:
      name:
        - "postgresql{{ PG_VER }}-server"
        - 'python3-module-psycopg2'

  - name: "Download Luxms BI Database and DS Infosec"
    shell: "apt-get clean all && apt-get install -y --download-only --reinstall luxmsbi-pg{{ PG_VER }} luxmsbi-pg-ds-infosec && mv /var/cache/apt/archives/*.rpm /opt/lux-upd/install/tmp/"

  - name: Changing the shell for the postgres user
    user:
      name: postgres
      shell: /bin/bash

  when: ansible_os_family == "Altlinux"


- name: Install PostgreSQL on MosOS
  block:

  - name: "Install PostgreSQL"
    zypper:
      name:
        - 'postgresql{{ PG_VER }}'
        - 'postgresql{{ PG_VER }}-server'
        - 'postgresql{{ PG_VER }}-contrib'
        - 'python3-psycopg2'
      state: present

  - name: "Download Luxms BI Database and DS Infosec"
    shell: "rm -rf /var/cache/zypp/packages/* && zypper in -y -d luxmsbi-pg{{ PG_VER }} luxmsbi-pg-ds-infosec && find /var/cache/zypp/packages -type f | xargs -I '{}' mv {} /opt/lux-upd/install/tmp/"

  when: ansible_os_family is match("MosOS*")


- name: Getting the postgres account settings
  user:
    name: postgres
    state: present
  register: user_postgres_info
  check_mode: true

- set_fact:
    PG_HOME: "{{ user_postgres_info.home }}"

- name: Setting up a postgres user profile (PGDATA)
  lineinfile:
    path: "{{ PG_HOME }}/.bash_profile"
    line: "export PGDATA=/data/pgdata"
    regexp: '^PGDATA=.*'
    create: yes
    owner: postgres
    group: postgres
    mode: 0600

- name: Setting up a postgres user profile (PATH)
  lineinfile:
    path: "{{ PG_HOME }}/.bash_profile"
    line: "export PATH={{ PG_BIN_DIR[ansible_os_family][ansible_distribution_major_version] }}:$PATH"
#    line: "export PATH={{ PG_BIN_DIR[ansible_os_family] }}:$PATH"

- name: Saving the file with the version of the installed PostgreSQL
  lineinfile:
    path: /opt/lux-upd/install/.installed
    line: "{{ PG_VER }}"
    create: yes