# roles/database/vars/main.yml
---

PG_SERVICE:
  RED: "postgresql-{{ PG_VER }}"
  REDOS: "postgresql-{{ PG_VER }}"
  Astra Linux: postgresql
  Altlinux: postgresql
  Rocky: postgresql
#  RedHat: postgresql
  RedHat:
    "8": postgresql
    "9": "postgresql-17"
  MosOS Arbat: postgresql
