---

- name: Загружаем задачи postgresql для более новыйх версий ansible
  include_tasks: postgresql_module.yml
  when: ansible_version.full is version("2.9", '>=')

- name: Загружаем задачи postgresql ansible версии ниже 2.9
  include_tasks: postgresql_shell.yml
  when: ansible_version.full is version("2.9", '<')

- name: "Прописываем переменную DATABORING_MASTER_JWT (RPM)"
  lineinfile:
    path: /etc/sysconfig/luxms-databoring
    regexp: '^DATABORING_MASTER_JWT='
    line: DATABORING_MASTER_JWT="{{ DATABORING_JWT }}"
  when: ansible_os_family is not match("Astra Linux*")

- name: "Прописываем переменную DATABORING_MASTER_JWT (DEB)"
  lineinfile:
    path: /etc/default/luxms-databoring
    regexp: '^DATABORING_MASTER_JWT='
    line: DATABORING_MASTER_JWT="{{ DATABORING_JWT }}"
  when: ansible_os_family is match("Astra Linux*")

- name: "Start systemd units on RPM"
  systemd:
    name: keydb
    enabled: true
    state: started
  when: ansible_os_family is not match("Astra Linux*")

- name: "Start systemd units on Astra Linux"
  systemd:
    name: keydb-server
    enabled: true
    state: started
  when: ansible_os_family is match("Astra Linux*")

- name: "Start systemd units"
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - nats-server
    - luxmsbi-web
    - luxmsbi-headless-chrome
    - luxmsbi-gateway
    - luxmsbi-appserver
    - luxms-databoring
    - luxmsbi-pumpushka
