---

- name: Меняем значение default_val для cfg_key, если у нас appserver mono
  shell: psql -d postgresql://bi:bi@127.0.0.1:5432/mi -c "UPDATE adm.configs SET default_val = 'http://127.0.0.1:8080' where cfg_key = 'datagate.url.prefix';"

- name: Get Databoring JWT-token
  shell: psql -d postgresql://bi:bi@127.0.0.1:5432/mi -t -c "SELECT jwt FROM webapi.access_tokens t left join adm.users u on t.login_as=u.id where u.username='databoring-service';"
  register: jwt_arr

- set_fact:
    DATABORING_JWT: "{{ jwt_arr.stdout | trim }}"

- name: Пампушка - Включаем параметры в adm.configs для её работы
  shell: psql -d postgresql://bi:bi@127.0.0.1:5432/mi -c "update adm.configs set is_enabled = '1', cfg_val = 'audit' where cfg_key = 'audit.tracking.topic';"