# ./roles/repo/tasks/debian.yml
---

- name: "Install Packages"
  apt:
    name:
    - curl
    state: present

- name: "Add DEB repositories"
  block:

  - name: Import keyserver.ubuntu.com repo keys
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 32E9750179FCEA62
      state: present

  - name: "Add Luxms BI repositories"
    import_tasks: set-luxms-apt-repo.yml

- name: "Install Postgresql"
  import_tasks: install-apt-postgresql.yml

- name: "Allow connection from all in pg_hba.conf"
  lineinfile:
    path: "{{ pg_hba_path }}"
    insertafter: '^host    all             all             127.0.0.1/32            md5'
    line: 'host    all             all             0.0.0.0/0               md5'

- name: Change listening address in postgres.conf
  lineinfile:
    path: "{{ postgresql_conf_path }}"
    insertafter: '^#listen_addresses '
    line: listen_addresses = '*'

- name: "Restart PostgreSQL service on ALSE"
  systemd:
    name: "{{ pg_srv_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: "Disable nginx vendor preset"
  lineinfile:
    dest: /lib/systemd/system-preset/90-systemd.preset
    line: "disable nginx.service"
    owner: root
    state: present
    insertafter: EOF
  become: yes

- name: "Set nginx preference Priority"
  copy:
    src: nginx.apt-preference
    dest: /etc/apt/preferences.d/nginx
    owner: root
    group: root
    mode: '0644'

- name: "Install supplementary packagies"
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop: "{{ pkg_list['supplementary'] }}"
