# roles/repo/tasks/main.yml
---

#- name: "Importing RPM-based tasks for RedHat"
#  include_tasks: redhat.yml
#  when :
#    ansible_os_family == "RedHat"

- name: "Importing RPM-based tasks for EL 8"
  include_tasks: el8.yml
  when :
    ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: "Importing RPM-based tasks for EL9 and PGDG15"
  include_tasks: el9.yml
  when :
    ansible_os_family == "RedHat" and ansible_distribution_major_version == "9" and PG_VER == "15"

- name: "Importing RPM-based tasks for EL9 and PGDG17"
  include_tasks: el9-pgdg17.yml
  when :
    ansible_os_family == "RedHat" and ansible_distribution_major_version == "9" and PG_VER == "17"

#- name: "Import RPM-based tasks for RED OS"
#  include_tasks: redos.yml
#  when :
#    ansible_os_family == "RED"

- name: "Import RPM-based tasks for REDOS 7"
  include_tasks: redos7.yml
  when :
    ansible_os_family == "REDOS" and ansible_distribution_major_version == "7"

- name: "Import RPM-based tasks for REDOS 8"
  include_tasks: redos8.yml
  when :
    ansible_os_family == "RED" and ansible_distribution_major_version == "8"

- name: "Import Deb-based tasks for Astra Linux 1.7"
  include_tasks: astra7.yml
  when:
    ansible_os_family == "Astra Linux" and ansible_distribution_major_version == "1.7*"

- name: "Import Deb-based tasks for Astra Linux 1.8"
  include_tasks: astra8.yml
  when:
    ansible_os_family == "Astra Linux" and ansible_distribution_major_version == "1"
