# ./roles/repo/tasks/redhat.yml
---

- name: "Adding Luxms BI repositories"
  import_tasks: set-luxms-yum-repo.yml

- name: "Adding supplementary YUM repositories"
  yum:
    name:
    - epel-release
    - centos-release-scl-rh
    - policycoreutils-python
    state: present
    validate_certs: no
  register: result
  retries: 5
  delay: 180
  until: result is not failed

- name: "Installing 'PostgreSQL'"
  import_tasks: install-yum-postgresql.yml

- name: "Registering Contents of 'PGDATA' Folder"
  shell: "ls {{ pd_data }}"
  register: pg_contents

# change 23-0607
- name: "Database 'PostgreSQL' initialization"
#  shell: "/usr/pgsql-{{ pg_ver }}/bin/initdb"
  shell: "/usr/pgsql-{{ pg_ver }}/bin/initdb"
  environment:
    PGDATA: "{{ pd_data }}"
  become: yes
  become_user: postgres
  when: pg_contents["stdout_lines"] | length == 0

# change 23-0609
#- name: "Init PostgreSQL DB"
##  shell: "/usr/pgsql-{{ pg_ver }}/bin/initdb"
##  shell: "/usr/bin/initdb"
#  shell: "/opt/pgpro/std-13/bin/pg-setup initdb"
#  environment:
#    PGDATA: "{{ pd_data }}"
#  become: yes
#  become_user: postgres
#  when: pg_contents["stdout_lines"] | length == 0

- name: "Changing listening address in 'postgresql.conf'"
  lineinfile:
    path: "{{ postgresql_conf_path }}"
    insertafter: '^#listen_addresses '
    line: listen_addresses = '*'

- name: "Allowing connection from all in 'pg_hba.conf'"
  lineinfile:
    path: "{{ pg_hba_path }}"
    insertafter: '^host    all             all             127.0.0.1/32            md5'
    line: 'host    all             all             0.0.0.0/0               md5'

- name: "Restarting PostgreSQL DB"
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: "{{ pg_srv_name }}"

- name: "Allowing services by 'firewalld'"
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
  - http
  - postgresql

- name: "Installing supplementary packagies"
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ pkg_list['supplementary'] }}"

- name: "Starting 'keydb' service"
  systemd:
    name: keydb.service
    state: started
    enabled: yes
    daemon_reload: yes
  when: "'keydb' in pkg_list['supplementary']"
