# ./roles/repo/tasks/set-luxms-yum-repo.yml
---
- name: "Coping 'IPA' certificates"
  copy:
    src: files/{{ item }}
    dest: /etc/pki/ca-trust/source/anchors
    owner: root
    group: root
    mode: '0644'
  with_items:
  - LuxmsCA.crt
  - ipaSubCA.crt

- name: "Updating root certificates: install ca-certificates"
  yum:
    name:
    - ca-certificates
    state: latest
    validate_certs: no

- name: "Updating root certificates: extract ca configuration"
  shell: /bin/update-ca-trust extract

- name: "Updating root certificates: update ca configuration"
  shell: /bin/update-ca-trust enable && /bin/update-ca-trust

- name: "Populating client repository 'luxmsbi.repo' yum template for external repo"
  template:
    src: templates/luxmsbi.repo.j2
    dest: /etc/yum.repos.d/luxmsbi.repo
    group: root
    owner: root
    mode: 0644
  register: luxmsbirepotemplate

- name: Clean out yum cache and recreate it again only if template was changed
  shell: "yum clean all && yum makecache"
  when: luxmsbirepotemplate.changed

- name: "Configuring the verification package: add 'RPM-GPG-Key-Luxms' file"
  copy:
    src: files/RPM-GPG-KEY-Luxms
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-Luxms
    group: root
    owner: root
    mode: 0644

- name: "Configuring the verification package: import 'RPM-GPG-Key-Luxms'"
  shell: rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-Luxms

#- name: "Disabling the repositories for 'luxms-bi'"
#  shell: "yum-config-manager --disable luxms-bi[0-9]"

#- name: "Enabling the repository 'luxms-bi' for version {{ bi_ver }}"
#  shell: "yum-config-manager --enable luxms-bi{{ bi_ver }}"
