# ./roles/deploy-bi/tasks/set-luxms-astra8-repo.yml
---

#- name: "Copying certificate files"
#  copy:
#    src: files/{{ item }}
#    dest: /etc/pki/ca-trust/source/anchors
#    owner: root
#    group: root
#    mode: '0644'
#  with_items:
#  - LuxmsCA.crt
#  - ipaSubCA.crt

#- name: "Root certificates: install ca-certificates"
#  apt:
#    name:
#    - ca-certificates
#    state: latest
#    validate_certs: no

#- name: "Root certificates: update"
#  shell: sudo apt update |& tee ~/${HOSTNAME}.apt_update."`date +%y%m%d-%H%M`".log

#- name: "Copying the configuration file 'sources.list' of the OS repository"
#  copy:
#    src: files/sources.list
#    dest: /etc/apt
#    group: root
#    owner: root
#    mode: 0644

- name: "Copying the configuration file 'luxmsbi.list' of the client repository 'luxmsbi'"
  copy:
    src: files/luxmsbi.list.astra8
    dest: /etc/apt/sources.list.d/luxmsbi.list
    group: root
    owner: root
    mode: 0644

- name: "Copying the login configuration file 'luxmsbi.conf'"
  copy:
    src: files/luxmsbi.conf
    dest: /etc/apt/auth.conf.d
    group: root
    owner: root
    mode: 0600

- name: "Clean out cache and recreate it again"
  shell: sudo apt update |& tee ~/${HOSTNAME}.apt_update."`date +%y%m%d-%H%M`".log

#- name: "Verifying the digital signature of packages: add a public PGP key 'RPM-GPG-Key-Luxms'"
#  copy:
#    src: files/RPM-GPG-KEY-Luxms
#    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-Luxms
#    group: root
#    owner: root
#    mode: 0644

- name: "Verifying the digital signature of packages: import a public PGP key 'RPM-GPG-Key-Luxms'"
  shell: sudo apt-key add /opt/lux-upd/install/roles/repo/files/RPM-GPG-KEY-Luxms
